version: "1"
rules:                      
  - base: master
    upstream: xmrig:master
    mergeMethod: merge
    mergeUnstable: true
#   - base: dev
#     upstream: master        # Required. Can be a branch in the same forked repo.
#     assignees:              # Optional
#       - kwamenf
#     reviewers:              # Optional
#       - kwamenf
#     conflictReviewers:      # Optional, on merge conflict assign a reviewer
#       - kwamenf
# label: ":arrow_heading_down: pull"  # Optional
# conflictLabel: "merge-conflict"     # Optional, on merge conflict assign a custom label, Default: merge-conflict
