name: Build
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Installation depends
      run: |
        git clone https://github.com/xmrig/xmrig-deps.git c:\xmrig-deps
        tree C:\xmrig-deps
    - name: Clone source code & build
      run: |
        git clone https://github.com/kwamenf/xmrig.git
        tree xmrig
        mkdir xmrig/build && cd xmrig\build
        dir
        cmake .. -G "Visual Studio 16 2019" -A x64 -DXMRIG_DEPS=c:\xmrig-deps\msvc2019\x64
        cmake --build . --config Release
        dir
    # - name : Upload artifact
    #   uses: actions/upload-artifact@master
    #   with:
    #     name: WinRing0x64
    #     path: xmrig/bin
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: xmrig
        path: xmrig/build/Release
